export const translate = {
     "en":{
        en:"English",
        ar:"Arabic",
        lang:"Language",
        train:"Train Station",
        home:"Home",
        blog:"Blog",
        find:"Find Your Perfect Train",
        about:"About",
        checkBalance:"CheckBalance",
        AddBalance:"AddBalance",
        LogOut:"LogOut",
        Perfect:"Perfect",
        Book:"Book a Ticket",
        Options:"Other Options",
        USP:"USP section",
        beverages :"beverages included",
        deals:"best deals",
        guarantee:"guarantee",
        readme:"read more",
        text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse interdum eleifend augue, quis rhoncus purus fermentum.",
        vist:"visitors experienced",
        sara:"Sara Connor",
        travel:"Travel Magazine",
        libro:"Nunc cursus libero purus ac congue arcu cursus ut sed vitae pulvinar massa idporta nequetiam nar...",
        manager:"Travel Manager",
        mira:"Mira Young",
        john:"John Smith",
        sed:"Suspendisse sed sollicitudin nisl, at dignissim libero. Sed porta tincidunt ipsum, vel volutpat.",
        footdown:"Nunc ut fringilla urna. Cras vel adipiscing ipsum. Integer dignissim nisl eu lacus interdum facilisis. Aliquam erat volutpat. Nulla",
        contact:"contact info",
        add:"address",
        hotel:"Hotel Finder",
        suite:"120 CA 15th Avenue-Suite 214, USA",
        Number:"phone number",
        email:"Email Address",
        pages:"pages",

     },
     "ar":{
        ar:"العربية",
        en:"الانجليزية",
        lang:"اللغة",
        train:"محطة القطار",
        home:"الرئيسية",
         blog:"مدونة",
         about:"حول",
         checkBalance:"تحقق من الرصيد",
         AddBalance:"إضافة رصيد",
         LogOut:"تسجيل الخروج",
         Perfect:"مثالي",
         Book:"احجز تذكرة",
         Options:"خيارات أخرى",
         USP:"قسم USP",
         beverages :"المشروبات مشمولة",
         deals:"أفضل العروض",
         guarantee:"ضمان",
         readme:"اقرأ المزيد",
     } 
}



